# 本文件采用 TOML 格式 https://toml.io/

# 文章标题 [请勿手动修改，会自动获取]
title = '''奇妙優美的漢語古文 -- 为什么古文不需要标点?'''

# 文章作者 [通常留空，自动等同于博客作者]
author = ''''''

# 文章创建时间
ctime = '2023-07-29 09:54:05+08:00'

# 文章修改时间
mtime = '2023-07-29 09:54:05+08:00'

# sha1, 用来判断文章内容有无变更 [请勿手动修改]
checksum = '6daf3f7fdbd17cf6415750a9fb8125f17d86478c'

# 是否忽略文章 (true/false)
# 被忽略的文章不出现在最近列表、索引列表里，但仍会出现在 RSS 里
ignored = false

# HTML中的图片的最大宽度 (留空表示跟随总设定)
img_width = '50%'

# 是否执行自动替换 (0:跟随总设定, -1:不执行, 1:执行)
replace = 0

# 自动替换。例:
# pairs =  [
#   [ '''../output/pics/abc.jpg''', '''https://example.com/abc.jpg''' ],
#   [ '''../output/pics/def.jpg''', '''https://example.com/def.jpg''' ],
# ]
pairs = [
  ['''../output/pics/guanzi01.jpg''', '''https://vip2.loli.io/2023/07/29/i2znjW8lJsvpmUC.jpg'''],
  ['''../output/pics/guanzi02.jpg''', '''https://vip2.loli.io/2023/07/29/AYMBbS1uamC95p2.jpg'''],
  ['''../output/pics/guanzi03.jpg''', '''https://vip2.loli.io/2023/07/29/w18eGbrYdL94cX3.jpg'''],
]
